<a href="https://colab.research.google.com/github/ngyoozheng-2025/Data-Science-Tutorials/blob/main/Tutorial_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Q1


In [41]:
import numpy as np

arrayQ1=np.array([[1,2],
               [3,4]])

print(arrayQ1)

[[1 2]
 [3 4]]


#Q2

In [40]:
import numpy as np

arrayQ2=np.random.rand(3,4)

print(arrayQ2)

[[0.1686403  0.28182731 0.26587666 0.61744486]
 [0.65781252 0.01149913 0.00960644 0.35612059]
 [0.06362218 0.66833731 0.89961541 0.62181954]]


#Q3

In [39]:
import numpy as np

arrayQ3a=np.ones((2,2))
arrayQ3b=np.zeros((2,2))

print(arrayQ3a, "\n\n", arrayQ3b)


[[1. 1.]
 [1. 1.]] 

 [[0. 0.]
 [0. 0.]]


#Q4

In [38]:
import numpy as np

arrayQ4a=np.random.rand(6,3)
arrayQ4b=arrayQ4a.T #or do np.transpose(arrayQ4a)

print(arrayQ4a, "\n\n", arrayQ4b)

[[0.74169379 0.58054331 0.98575085]
 [0.3051024  0.9558924  0.24205084]
 [0.36636675 0.30828363 0.49139504]
 [0.04591177 0.87437325 0.07861029]
 [0.98427556 0.1387099  0.60152485]
 [0.81967245 0.40346538 0.50829889]] 

 [[0.74169379 0.3051024  0.36636675 0.04591177 0.98427556 0.81967245]
 [0.58054331 0.9558924  0.30828363 0.87437325 0.1387099  0.40346538]
 [0.98575085 0.24205084 0.49139504 0.07861029 0.60152485 0.50829889]]


#Q5

In [37]:
import numpy as np
n=int(input("Enter n: "))
p=int(input("Enter p: "))

arrayQ5a=np.random.rand(n,p)
arrayQ5b=np.random.rand(p,n)
arrayQ5c=np.dot(arrayQ5a, arrayQ5b)

print (arrayQ5a, "\n\n", arrayQ5b, "\n\n", arrayQ5c)

Enter n: 4
Enter p: 6
[[0.84770057 0.58824665 0.11962427 0.80047868 0.60746833 0.60603884]
 [0.1266482  0.35923834 0.78656728 0.1974542  0.62473959 0.12974424]
 [0.73052824 0.43737681 0.07291186 0.89824148 0.85779003 0.35670977]
 [0.00305978 0.09198817 0.92979415 0.79389403 0.65954702 0.32517216]] 

 [[0.26715194 0.90255227 0.85593045 0.01587059]
 [0.93936663 0.39476895 0.12269063 0.84274997]
 [0.70397276 0.75885042 0.91441972 0.62157697]
 [0.57624157 0.4783454  0.87379042 0.83615235]
 [0.70073133 0.83144608 0.66552643 0.31269843]
 [0.09062543 0.92093461 0.58779347 0.68426327]] 

 [[1.80512007 2.53419711 2.36709438 1.85752069]
 [1.4883268  1.58638422 1.53630697 1.24290628]
 [1.80835858 2.35871411 2.31104386 1.68889326]
 [1.69088667 1.972246   2.18790419 1.74806926]]
